AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue de prueba tecnica

Resources:
  BackendEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: fund-manager
      ImageId: ami-0a91cd140a1fc148a
      SecurityGroupIds:
        - !Ref BackendSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 git
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user
          curl -sSL https://get.docker.com/ | sh
          systemctl start docker
          systemctl enable docker
          # Instalar aws-cli
          yum install -y aws-cli
          # Obtener las variables de entorno desde Parameter Store
          VARIABLES=(VERSION GMAIL_FROM_EMAIL GMAIL_EMAIL_PASSWORD GMAIL_SMTP_SERVER GMAIL_SMTP_PORT TWILIO_ACCOUNT_SID TWILIO_AUTH_TOKEN TWILIO_PHONE aws_access_key_id aws_secret_access_key region_name)
          ENV_FILE="/home/ec2-user/.env"
          touch $ENV_FILE
          # Obtener cada variable de Parameter Store y agregarla al archivo .env
          for VAR in "${VARIABLES[@]}"
          do
              VALUE=$(aws ssm get-parameter --name "$VAR" --with-decryption --query "Parameter.Value" --output text --region ${AWS::Region})
              echo "$VAR=$VALUE" >> $ENV_FILE
          done
          echo "Archivo .env creado con éxito en /home/ec2-user/.env"
          # Clonar el repositorio y ejecutar la aplicación
          git clone https://github.com/SebastianCl/fund_manager-back.git
          cd fund_manager-back
          pip3 install -r requirements.txt
          uvicorn main:app --host 0.0.0.0 --port 80

  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acceso HTTP y SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyTable2
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

