AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    DynamoTableName:
        Type: String
    DynamoTableKey:
        Type: String
      
Resources:
  Dynamo:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Ref DynamoTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: !Ref DynamoTableKey
        AttributeType: S
      KeySchema:
      - AttributeName: !Ref DynamoTableKey
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true
Outputs:
  Dynamo:
      Value: !Ref Dynamo
      Export:
        Name: Dynamo
  DynamoArn:
      Value: !GetAtt Dynamo.Arn
      Export:
        Name: DynamoArn